### PR TITLE
enable kill child process

### PR DESCRIPTION
**Pull request by AckerApple**
I need the ability to abort an AppleScript. 

For me, I have an always running AppleScript process governed by node-osascript and at times I need to kill the AppleScript while keeping the node process alive.

For most others, this pull request allows them to have a timeout

Updated the README

Thank you much for this great package.

### CODE REVIEW

**Comment by AckerApple** [comment]
Anyone? Can we get this pulled and published?

**Comment by FWeinb** [comment]
Was in the middle of writing my bachelor's thesis. Will release it as 2.1.0 because this is a new feature.

**Comment by AckerApple** [comment]
Fantastic! Thank you much. I’ve been running off my fork for the meantime so no big deal.

**Comment by AckerApple** [comment]
Please publish to npm when you get a chance

**Comment by FWeinb** [comment]
[Released in 2.1.0](https://www.npmjs.com/package/node-osascript)

**Comment by AckerApple** [comment]
NPM has a delay I suppose. I don’t see the new version yet. This has been happening with my own packages over the last couple weeks.

It’ll update soon I’m sure

**Pull request merged**
